{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           AssertionError: Unexpected message in Update Contribution: Return contribution added successfully.\n           assert 'Return contr...successfully.' == 'Contribution...successfully.'\n             \n             - Contribution updated successfully.\n             ? ^            ^^ ^^\n             + Return contribution added successfully.\n             ? ^^^^^^^^            ^ ^\n", "test_name": "test_add_contribution", "rerun": "0"}}, "suite_name": "main/test_transactions.py"}}}, "date": "December 09, 2024", "start_time": 1733747263.665073, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}